name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
        - name: trigger dispatch
          run:  |
            curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.GLOBAL_PAT }}" \
               https://api.github.com/repos/mradwan80/RepoB/actions/workflows/ci.yml/dispatches \
               -d '{"ref": "workflow-dispatch", "inputs": {}}'
